apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/quantum-toolbox-230214/github.com/shaz001/kubernetes-intro:$TAG_NAME
        ports:
        - containerPort: 5000
