apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/quantum-toolbox-230214/github.com/shaz001/kubernetes-intro:$TAG_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
